const GETLIST = "GETLIST"
const GET_LIST_SUCCESS = "GET_LIST_SUCCESS"
const SHOW_TODO_lIST = "SHOW_TODO_lIST"
const DELETE_TODO_REQ = "DELETE_TODO_REQ"
// const DELETE_SUCCESS = 'REMOVVE';
const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
const ADD_REQUEST = "ADD_REQUEST"
const REMOVE = "REMOVE"
export const Types = {
    GETLIST, GET_LIST_SUCCESS, SHOW_TODO_lIST, DELETE_TODO_REQ,  UPDATE_SUCCESS, REMOVE, ADD_REQUEST
}